/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as DaemonRouteImport } from './routes/daemon'
import { Route as HwihfRouteImport } from './routes/hwihf'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LinksRouteImport } from './routes/links'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as UseCasesRouteImport } from './routes/use-cases'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const DaemonRoute = DaemonRouteImport.update({
  id: '/daemon',
  path: '/daemon',
  getParentRoute: () => rootRouteImport,
} as any)
const HwihfRoute = HwihfRouteImport.update({
  id: '/hwihf',
  path: '/hwihf',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/daemon': typeof DaemonRoute
  '/hwihf': typeof HwihfRoute
  '/legal': typeof LegalRoute
  '/links': typeof LinksRoute
  '/models': typeof ModelsRoute
  '/security': typeof SecurityRoute
  '/tools': typeof ToolsRoute
  '/use-cases': typeof UseCasesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/daemon': typeof DaemonRoute
  '/hwihf': typeof HwihfRoute
  '/legal': typeof LegalRoute
  '/links': typeof LinksRoute
  '/models': typeof ModelsRoute
  '/security': typeof SecurityRoute
  '/tools': typeof ToolsRoute
  '/use-cases': typeof UseCasesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/daemon': typeof DaemonRoute
  '/hwihf': typeof HwihfRoute
  '/legal': typeof LegalRoute
  '/links': typeof LinksRoute
  '/models': typeof ModelsRoute
  '/security': typeof SecurityRoute
  '/tools': typeof ToolsRoute
  '/use-cases': typeof UseCasesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/daemon'
    | '/hwihf'
    | '/legal'
    | '/links'
    | '/models'
    | '/security'
    | '/tools'
    | '/use-cases'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/daemon'
    | '/hwihf'
    | '/legal'
    | '/links'
    | '/models'
    | '/security'
    | '/tools'
    | '/use-cases'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/daemon'
    | '/hwihf'
    | '/legal'
    | '/links'
    | '/models'
    | '/security'
    | '/tools'
    | '/use-cases'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  DaemonRoute: typeof DaemonRoute
  HwihfRoute: typeof HwihfRoute
  LegalRoute: typeof LegalRoute
  LinksRoute: typeof LinksRoute
  ModelsRoute: typeof ModelsRoute
  SecurityRoute: typeof SecurityRoute
  ToolsRoute: typeof ToolsRoute
  UseCasesRoute: typeof UseCasesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daemon': {
      id: '/daemon'
      path: '/daemon'
      fullPath: '/daemon'
      preLoaderRoute: typeof DaemonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hwihf': {
      id: '/hwihf'
      path: '/hwihf'
      fullPath: '/hwihf'
      preLoaderRoute: typeof HwihfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  DaemonRoute: DaemonRoute,
  HwihfRoute: HwihfRoute,
  LegalRoute: LegalRoute,
  LinksRoute: LinksRoute,
  ModelsRoute: ModelsRoute,
  SecurityRoute: SecurityRoute,
  ToolsRoute: ToolsRoute,
  UseCasesRoute: UseCasesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
